language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script: echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini && composer install --dev
script: ./vendor/bin/phpunit -c phpunit.xml.dist test/
